# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 066bf5e74685a346d9e0bfa78467f0964c603cb7a96a14d1a24fe368b43b9fc9180742c11cb5345e07821e1bf7035d97ec07c63e25f9f46df5324b4caff94e52

test:
  secret_key_base: 77e5cd2f0d4b4b2ef0b82f48b81c8e109a21fe5b20cc271c71204d75869c346fac9ebdf8478d1b8057f8939f6ab97427f01f9fe969acaf182d4a4e82ac7a6da0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
